[package]
name = "rust-commit2-worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.70", features = ["backtrace"] }
clap = { version = "4.1.11", features = ["env", "derive"] }
home = "0.5.4"
lazy_static = "1.4.0"
log = "0.4.17"
time = { version = "0.3.20", features = ["formatting"] }
